### ISSUE TITLE
Gif Editing

### ISSUE THREAD

**Issue by Vaestro** [kaishin/Gifu#100]
Is it possible to edit GIFs using Gifu?

How I imagined this could work was if I let the User edit each frame using the activeFrame() method and then save the GIF. But now I realize activeFrame() is a read-only method. Is there anyway I can edit GIFs using GIFu and more specifically, is there a way to add text to a GIF to create a GIF meme?

**Comment by kaishin** [comment]
I am afraid editing GIFs or adding text is out of scope for Gifu. The only purpose of Gifu is parsing GIF data and showing the frames in succession. Editing a frame would re-use very little of the current codebase.

**Comment by Vaestro** [comment]
Thank you for answering. Do you know of any libraries I can use to help me edit GIFs? I've been searching around for a while and I'm a little lost for a solution.
