### ISSUE TITLE
Is deprecated 'FLT_EPSILON'

### ISSUE THREAD

**Issue by nikolaenkoag** [kaishin/Gifu#110]
Hi! In file ImageSourceHelpers.swift 'FLT_EPSILON' is deprecated. Recommendations for use 'Float.ulpOfOne' or '.ulpOfOne'.

**Comment by neokree** [comment]
Same here, @kaishin could you please upload a hotfix for this? 

Gifu version: 2.0.0
XCode: 8.3.3
Swift: 3.1

**Comment by kaishin** [comment]
Please update to `v2.0.1` which was just released. An oversight on my part.
