### ISSUE TITLE
Support for Swift 4?

### ISSUE THREAD

**Issue by petaire92** [kaishin/Gifu#114]
Hey! 
Thanks for Gifu. Any chance to have a Swift 4 compatible one soon?

**Comment by jlaws** [comment]
Any update on this?

**Comment by jpm-polymorph** [comment]
I see mentioned in the commit messages that swift 4 support was added, but there has been no release after that. @kaishin if the Swift 4 support is ready, do you mind making a release?

**Comment by jlaws** [comment]
@kaishin Would be great to have Swift 4 be the latest podspec

**Comment by ninjagal21** [comment]
Hello, any updates?

**Comment by kaishin** [comment]
The `master` branch is already compatible with Swift 4. A proper release will be made asap.

**Comment by kaishin** [comment]
As of https://github.com/kaishin/Gifu/releases/tag/v3.0.0 Gifu is fully Swift 4 compatible.
