### ISSUE TITLE
Patch release?

### ISSUE THREAD

**Issue by ashfurrow** [kaishin/Gifu#117]
Hello! I'm having some problems compiling projects integrated with Gifu 2.0.1 using Xcode 9.1:

![screen shot 2017-11-04 at 7 47 10 pm](https://user-images.githubusercontent.com/498212/32410642-2ac982e2-c19c-11e7-9c0c-30fcde9ec6de.png)

I can point CocoaPods at master, where the issue was fixed:

https://github.com/kaishin/Gifu/commit/50a9851d556240fe7341755c3b8ea207b142a803#diff-6f9d3282986dd930b9aeb8a34eda7dbaR96

Would you consider release a new version of Gifu that includes this patch? Thanks!

**Comment by ashfurrow** [comment]
Hey just following on up this – any chance we could get a patch release? Thanks!

**Comment by kaishin** [comment]
@ashfurrow Thank for your patience. I had some catching up to do with Gifu. I will try to get a `3.0` out asap.

**Comment by kaishin** [comment]
https://github.com/kaishin/Gifu/releases/tag/v3.0.0

**Comment by ashfurrow** [comment]
Cool, thanks for the follow-up. Have a good 2018!
