### ISSUE TITLE
crash from crashlytics

### ISSUE THREAD

**Issue by mahmutsahinn** [kaishin/Gifu#118]
Hi, i got an error like this from crashlytics, do you have any idea? Thank you

#0. Crashed: com.twitter.crashlytics.ios.exception
0  Hesabim                        0x1007c8350 CLSProcessRecordAllThreads + 453704
1  Hesabim                        0x1007c8350 CLSProcessRecordAllThreads + 453704
2  Hesabim                        0x1007c820c CLSProcessRecordAllThreads + 453380
3  Hesabim                        0x1007b8338 CLSHandler + 388144
4  Hesabim                        0x1007c6368 __CLSExceptionRecord_block_invoke + 445536
5  libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1811b7ee0 _dispatch_barrier_sync_f_invoke + 84
7  Hesabim                        0x1007c5dfc CLSExceptionRecord + 444148
8  Hesabim                        0x1007c5c24 CLSExceptionRecordNSException + 443676
9  Hesabim                        0x1007c5838 CLSTerminateHandler() + 442672
10 libc++abi.dylib                0x180d435d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x180d42ef8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x180d5466c _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x1822f9ef4 __methodDescriptionForSelector + 138
14 CoreFoundation                 0x1822f6f54 ___forwarding___ + 916
15 CoreFoundation                 0x1821f2d4c _CF_forwarding_prep_0 + 92
16 UIKit                          0x1887c4b18 -[UIImageView _updateImageViewForOldImage:newImage:] + 296
17 UIKit                          0x1884322bc -[UIImageView setImage:] + 340
18 Gifu                           0x101a1e0ec _T0So11UIImageViewC4Gifu14ImageContainerA2cDP5imageSo0A0CSgfsTW + 56
19 Gifu                           0x101a1c104 _T04Gifu13GIFAnimatablePAAE19updateImageIfNeededyyFAA12GIFImageViewC_Tg5 + 256
20 Gifu                           0x101a1c664 _T04Gifu12GIFImageViewC7displayySo7CALayerCFTo + 36
21 QuartzCore                     0x185611098 CA::Layer::display() + 140
22 QuartzCore                     0x185606c20 CA::Layer::display_if_needed(CA::Transaction*) + 228
23 QuartzCore                     0x185606cb4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 44
24 QuartzCore                     0x18558234c CA::Context::commit_transaction(CA::Transaction*) + 252
25 QuartzCore                     0x1855a93ac CA::Transaction::commit() + 504
26 QuartzCore                     0x185505530 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 600
27 IOKit                          0x18255fb9c IODispatchCalloutFromCFMessage + 372
28 CoreFoundation                 0x182289960 __CFMachPortPerform + 180
29 CoreFoundation                 0x1822a1ae4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
30 CoreFoundation                 0x1822a1284 __CFRunLoopDoSource1 + 436
31 CoreFoundation                 0x18229ed98 __CFRunLoopRun + 1752
32 CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
33 GraphicsServices               0x183c39074 GSEventRunModal + 100
34 UIKit                          0x188489c9c UIApplicationMain + 208
35 Hesabim                        0x10062c6c4 main (main.swift:20)
36 libdyld.dylib                  0x1811dd59c start + 4

--

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1822f2fe0 __exceptionPreprocess
1  libobjc.A.dylib                0x180d54538 objc_exception_throw
2  CoreFoundation                 0x1822f9ef4 __methodDescriptionForSelector
3  CoreFoundation                 0x1822f6f54 ___forwarding___
4  CoreFoundation                 0x1821f2d4c _CF_forwarding_prep_0
5  UIKit                          0x1887c4b18 -[UIImageView _updateImageViewForOldImage:newImage:]
6  UIKit                          0x1884322bc -[UIImageView setImage:]
7  Gifu                           0x101a1e0ec (Missing)
8  Gifu                           0x101a1c104 (Missing)
9  Gifu                           0x101a1c664 _T04Gifu12GIFImageViewC7displayySo7CALayerCFTo
10 QuartzCore                     0x185611098 CA::Layer::display()
11 QuartzCore                     0x185606c20 CA::Layer::display_if_needed(CA::Transaction*)
12 QuartzCore                     0x185606cb4 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
13 QuartzCore                     0x18558234c CA::Context::commit_transaction(CA::Transaction*)
14 QuartzCore                     0x1855a93ac CA::Transaction::commit()
15 QuartzCore                     0x185505530 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
16 IOKit                          0x18255fb9c IODispatchCalloutFromCFMessage
17 CoreFoundation                 0x182289960 __CFMachPortPerform
18 CoreFoundation                 0x1822a1ae4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
19 CoreFoundation                 0x1822a1284 __CFRunLoopDoSource1
20 CoreFoundation                 0x18229ed98 __CFRunLoopRun
21 CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific
22 GraphicsServices               0x183c39074 GSEventRunModal
23 UIKit                          0x188489c9c UIApplicationMain
24 Hesabim                        0x10062c6c4 main (main.swift:20)
25 libdyld.dylib                  0x1811dd59c start

#0. Crashed: com.twitter.crashlytics.ios.exception
0  Hesabim                        0x1007c8350 CLSProcessRecordAllThreads + 453704
1  Hesabim                        0x1007c8350 CLSProcessRecordAllThreads + 453704
2  Hesabim                        0x1007c820c CLSProcessRecordAllThreads + 453380
3  Hesabim                        0x1007b8338 CLSHandler + 388144
4  Hesabim                        0x1007c6368 __CLSExceptionRecord_block_invoke + 445536
5  libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1811b7ee0 _dispatch_barrier_sync_f_invoke + 84
7  Hesabim                        0x1007c5dfc CLSExceptionRecord + 444148
8  Hesabim                        0x1007c5c24 CLSExceptionRecordNSException + 443676
9  Hesabim                        0x1007c5838 CLSTerminateHandler() + 442672
10 libc++abi.dylib                0x180d435d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x180d42ef8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 134
12 libobjc.A.dylib                0x180d5466c _objc_exception_destructor(void*) + 362
13 CoreFoundation                 0x1822f9ef4 __methodDescriptionForSelector + 138
14 CoreFoundation                 0x1822f6f54 ___forwarding___ + 916
15 CoreFoundation                 0x1821f2d4c _CF_forwarding_prep_0 + 92
16 UIKit                          0x1887c4b18 -[UIImageView _updateImageViewForOldImage:newImage:] + 296
17 UIKit                          0x1884322bc -[UIImageView setImage:] + 340
18 Gifu                           0x101a1e0ec _T0So11UIImageViewC4Gifu14ImageContainerA2cDP5imageSo0A0CSgfsTW + 56
19 Gifu                           0x101a1c104 _T04Gifu13GIFAnimatablePAAE19updateImageIfNeededyyFAA12GIFImageViewC_Tg5 + 256
20 Gifu                           0x101a1c664 _T04Gifu12GIFImageViewC7displayySo7CALayerCFTo + 36
21 QuartzCore                     0x185611098 CA::Layer::display() + 140
22 QuartzCore                     0x185606c20 CA::Layer::display_if_needed(CA::Transaction*) + 228
23 QuartzCore                     0x185606cb4 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 44
24 QuartzCore                     0x18558234c CA::Context::commit_transaction(CA::Transaction*) + 252
25 QuartzCore                     0x1855a93ac CA::Transaction::commit() + 504
26 QuartzCore                     0x185505530 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 600
27 IOKit                          0x18255fb9c IODispatchCalloutFromCFMessage + 372
28 CoreFoundation                 0x182289960 __CFMachPortPerform + 180
29 CoreFoundation                 0x1822a1ae4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
30 CoreFoundation                 0x1822a1284 __CFRunLoopDoSource1 + 436
31 CoreFoundation                 0x18229ed98 __CFRunLoopRun + 1752
32 CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
33 GraphicsServices               0x183c39074 GSEventRunModal + 100
34 UIKit                          0x188489c9c UIApplicationMain + 208
35 Hesabim                        0x10062c6c4 main (main.swift:20)
36 libdyld.dylib                  0x1811dd59c start + 4

#1. com.apple.NSURLSession-work
0  libsystem_kernel.dylib         0x1812d05c4 fstat + 8
1  CFNetwork                      0x182b578d8 CFURLCacheFS::getCachedResponseDataFromFS(void**, long*) + 128
2  CFNetwork                      0x18299ec2c __CFURLCache::bindExternalDataToCachedResponse(_CFCachedURLResponse const*, __CFString const*, __CFString const*) + 96
3  CFNetwork                      0x18299e7a0 __CFURLCache::calloutForAsyncDiskCache(__CFString const*, _CFURLRequest const*, NSURLSession const*, void (_CFCachedURLResponse const*) block_pointer) + 252
4  CFNetwork                      0x18299aae0 __CFURLCache::CopyResponseForRequestWithCompletionHandler(_CFURLRequest const*, bool, NSURLSession const*, void (_CFCachedURLResponse const*) block_pointer) + 648
5  CFNetwork                      0x182b07b18 CFXURLCache::getResponseForTask(NSURLSessionTask const*, unsigned char, void (_CFCachedURLResponse const*) block_pointer) const + 84
6  CFNetwork                      0x182a86718 URLConnectionLoader::_loaderEvent_StartLoad(NSURLSessionTask const*) + 988
7  CFNetwork                      0x1829cc53c -[__NSCFURLLocalSessionConnection withLoaderOnQueue:] + 72
8  CFNetwork                      0x1829ccb3c -[__NSCFURLLocalSessionConnection _tick_initialize] + 88
9  CFNetwork                      0x1829cc0f0 __71-[__NSCFURLLocalSessionConnection initWithTask:delegate:delegateQueue:]_block_invoke + 40
10 libdispatch.dylib              0x1811aa9e0 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1811b8ad4 _dispatch_queue_serial_drain + 928
13 libdispatch.dylib              0x1811ae2cc _dispatch_queue_invoke + 884
14 libdispatch.dylib              0x1811b8fa8 _dispatch_queue_override_invoke + 344
15 libdispatch.dylib              0x1811baa50 _dispatch_root_queue_drain + 540
16 libdispatch.dylib              0x1811ba7d0 _dispatch_worker_thread3 + 124
17 libsystem_pthread.dylib        0x1813b3100 _pthread_wqthread + 1096
18 libsystem_pthread.dylib        0x1813b2cac start_wqthread + 4

#2. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1812cf224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1812cf09c mach_msg + 72
2  CoreFoundation                 0x1822a0e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18229eae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
5  Foundation                     0x182ce9db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x182d0ab84 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x188e13830 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x182de7318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
10 libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
11 libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#3. co.kaishin.Gifu.preloadQueue
0  libsystem_malloc.dylib         0x181326b6c free_large + 516
1  libsystem_malloc.dylib         0x1813269cc free_large + 100
2  ImageIO                        0x184104d04 _cg_DGifCloseFile + 192
3  ImageIO                        0x184146e9c GIFReadPlugin::init() + 736
4  ImageIO                        0x184149180 GIFReadPlugin::InitProc(CGImagePlugin*, unsigned long, unsigned long) + 92
5  ImageIO                        0x183f7c59c IIOImageSource::makeImagePlus(unsigned long, __CFDictionary const*) + 1084
6  ImageIO                        0x183f7d514 IIOImageSource::getPropertiesAtIndexInternal(unsigned long, __CFDictionary const*) + 68
7  ImageIO                        0x183f7d494 IIOImageSource::copyPropertiesAtIndex(unsigned long, __CFDictionary const*) + 100
8  ImageIO                        0x183f800c4 CGImageSourceCopyPropertiesAtIndex + 188
9  Gifu                           0x101a1d1b0 _T0So13CGImageSourceC4GifuE10propertiess10DictionaryVySSSdGSgSi2at_tF + 52
10 Gifu                           0x101a1aed8 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_Tf4gn_n + 412
11 Gifu                           0x101a1ad28 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_TA + 68
12 Gifu                           0x101a18c1c _T0Ix_IyB_TR + 36
13 libdispatch.dylib              0x1811aa9e0 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1811b8ad4 _dispatch_queue_serial_drain + 928
16 libdispatch.dylib              0x1811ae2cc _dispatch_queue_invoke + 884
17 libdispatch.dylib              0x1811b8fa8 _dispatch_queue_override_invoke + 344
18 libdispatch.dylib              0x1811baa50 _dispatch_root_queue_drain + 540
19 libdispatch.dylib              0x1811ba7d0 _dispatch_worker_thread3 + 124
20 libsystem_pthread.dylib        0x1813b3100 _pthread_wqthread + 1096
21 libsystem_pthread.dylib        0x1813b2cac start_wqthread + 4

#4. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x1812cf224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1812cf09c mach_msg + 72
2  Hesabim                        0x1007b3208 CLSMachExceptionServer + 367360
3  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
4  libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
5  libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#5. Thread
0  libsystem_pthread.dylib        0x1813b2ca8 start_wqthread + 126

#6. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1812cf224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1812cf09c mach_msg + 72
2  CoreFoundation                 0x1822a0e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18229eae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x1829dbdf4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x182de7318 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
8  libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
9  libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#7. NSOperationQueue 0x170420560 :: NSOperation 0x17025ba20 (QOS: DEFAULT)
0  libsystem_kernel.dylib         0x1812ed314 __semwait_signal + 8
1  libsystem_c.dylib              0x18120c8b0 nanosleep + 212
2  Foundation                     0x182de65d0 +[NSThread sleepForTimeInterval:] + 136
3  Hesabim                        0x1000ee00c __23-[CurioPostOffice init]_block_invoke (CurioPostOffice.m:590)
4  Foundation                     0x182dc2854 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
5  Foundation                     0x182d077b0 -[NSBlockOperation main] + 96
6  Foundation                     0x182cf7b68 -[__NSOperationInternal _start:] + 612
7  Foundation                     0x182dc4bf0 __NSOQSchedule_f + 228
8  libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
9  libdispatch.dylib              0x1811b8ad4 _dispatch_queue_serial_drain + 928
10 libdispatch.dylib              0x1811ae2cc _dispatch_queue_invoke + 884
11 libdispatch.dylib              0x1811baa50 _dispatch_root_queue_drain + 540
12 libdispatch.dylib              0x1811ba7d0 _dispatch_worker_thread3 + 124
13 libsystem_pthread.dylib        0x1813b3100 _pthread_wqthread + 1096
14 libsystem_pthread.dylib        0x1813b2cac start_wqthread + 4

#8. AFNetworking
0  libsystem_kernel.dylib         0x1812cf224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1812cf09c mach_msg + 72
2  CoreFoundation                 0x1822a0e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18229eae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
5  Foundation                     0x182ce9db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x182d3e704 -[NSRunLoop(NSRunLoop) run] + 88
7  Hesabim                        0x100b97fd0 TLAFQueryStringPairsFromKeyAndValue + 541076
8  Foundation                     0x182de7318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
10 libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
11 libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#9. GAIThread
0  libsystem_kernel.dylib         0x1812cf224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1812cf09c mach_msg + 72
2  CoreFoundation                 0x1822a0e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18229eae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
5  Foundation                     0x182ce9db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x182d3e704 -[NSRunLoop(NSRunLoop) run] + 88
7  Hesabim                        0x1006d3f30 +[GAI threadMain:] + 4302192432
8  Foundation                     0x182de7318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
10 libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
11 libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#10. Thread
0  libsystem_kernel.dylib         0x1812ece1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1813b4814 _pthread_cond_wait + 640
2  libc++.1.dylib                 0x180cddac8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x186b82f08 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 112
4  JavaScriptCore                 0x186b82e7c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 168
5  JavaScriptCore                 0x186b82d5c std::__1::__shared_ptr_emplace<std::__1::mutex, std::__1::allocator<std::__1::mutex> >::~__shared_ptr_emplace() + 34
6  JavaScriptCore                 0x186b8300c void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 92
7  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
8  libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
9  libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#11. WebThread
0  libsystem_kernel.dylib         0x1812cf224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1812cf09c mach_msg + 72
2  CoreFoundation                 0x1822a0e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18229eae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
5  WebCore                        0x186ea0d3c RunWebThread(void*) + 456
6  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
7  libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
8  libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#12. AFNetworking
0  libsystem_kernel.dylib         0x1812cf224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1812cf09c mach_msg + 72
2  CoreFoundation                 0x1822a0e90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18229eae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1821ceda4 CFRunLoopRunSpecific + 424
5  Foundation                     0x182ce9db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x182d3e704 -[NSRunLoop(NSRunLoop) run] + 88
7  Hesabim                        0x100c4c42c +[RBMAFURLConnectionOperation networkRequestThreadEntryPoint:] + 1279472
8  Foundation                     0x182de7318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x1813b568c _pthread_body + 240
10 libsystem_pthread.dylib        0x1813b559c _pthread_body + 282
11 libsystem_pthread.dylib        0x1813b2cb4 thread_start + 4

#13. co.kaishin.Gifu.preloadQueue
0  libswiftCore.dylib             0x1027c8b10 searchInConformanceCache(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*) + 260
1  libswiftCore.dylib             0x1027c876c swift_conformsToProtocol + 72
2  libswiftCore.dylib             0x1027c876c swift_conformsToProtocol + 72
3  libswiftCore.dylib             0x1027b1408 swift_dynamicCast + 1624
4  libswiftCore.dylib             0x1027b0fe8 swift_dynamicCast + 568
5  Gifu                           0x101a1d510 _T0So13CGImageSourceC4GifuE10propertiess10DictionaryVySSSdGSgSi2at_tF + 916
6  Gifu                           0x101a1aed8 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_Tf4gn_n + 412
7  Gifu                           0x101a1ad28 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_TA + 68
8  Gifu                           0x101a18c1c _T0Ix_IyB_TR + 36
9  libdispatch.dylib              0x1811aa9e0 _dispatch_call_block_and_release + 24
10 libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
11 libdispatch.dylib              0x1811b8ad4 _dispatch_queue_serial_drain + 928
12 libdispatch.dylib              0x1811ae2cc _dispatch_queue_invoke + 884
13 libdispatch.dylib              0x1811b8fa8 _dispatch_queue_override_invoke + 344
14 libdispatch.dylib              0x1811baa50 _dispatch_root_queue_drain + 540
15 libdispatch.dylib              0x1811ba7d0 _dispatch_worker_thread3 + 124
16 libsystem_pthread.dylib        0x1813b3100 _pthread_wqthread + 1096
17 libsystem_pthread.dylib        0x1813b2cac start_wqthread + 4

#14. Thread
0  libsystem_pthread.dylib        0x1813b2ca8 start_wqthread + 126

#15. co.kaishin.Gifu.preloadQueue
0  libsystem_kernel.dylib         0x1812cf170 _kernelrpc_mach_vm_map_trap + 8
1  libsystem_kernel.dylib         0x1812d02f4 mach_vm_map + 116
2  libsystem_malloc.dylib         0x181326734 allocate_pages + 224
3  libsystem_malloc.dylib         0x181326384 large_malloc + 144
4  libsystem_malloc.dylib         0x1813217e8 szone_malloc_should_clear + 276
5  libsystem_malloc.dylib         0x181321664 malloc_zone_malloc + 172
6  libsystem_malloc.dylib         0x18132456c malloc + 32
7  ImageIO                        0x184103df4 _cg_DGifOpen + 76
8  ImageIO                        0x184146c70 GIFReadPlugin::init() + 180
9  ImageIO                        0x184149180 GIFReadPlugin::InitProc(CGImagePlugin*, unsigned long, unsigned long) + 92
10 ImageIO                        0x183f7c59c IIOImageSource::makeImagePlus(unsigned long, __CFDictionary const*) + 1084
11 ImageIO                        0x183f7d514 IIOImageSource::getPropertiesAtIndexInternal(unsigned long, __CFDictionary const*) + 68
12 ImageIO                        0x183f7d494 IIOImageSource::copyPropertiesAtIndex(unsigned long, __CFDictionary const*) + 100
13 ImageIO                        0x183f800c4 CGImageSourceCopyPropertiesAtIndex + 188
14 Gifu                           0x101a1d1b0 _T0So13CGImageSourceC4GifuE10propertiess10DictionaryVySSSdGSgSi2at_tF + 52
15 Gifu                           0x101a1aed8 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_Tf4gn_n + 412
16 Gifu                           0x101a1ad28 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_TA + 68
17 Gifu                           0x101a18c1c _T0Ix_IyB_TR + 36
18 libdispatch.dylib              0x1811aa9e0 _dispatch_call_block_and_release + 24
19 libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
20 libdispatch.dylib              0x1811b8ad4 _dispatch_queue_serial_drain + 928
21 libdispatch.dylib              0x1811ae2cc _dispatch_queue_invoke + 884
22 libdispatch.dylib              0x1811b8fa8 _dispatch_queue_override_invoke + 344
23 libdispatch.dylib              0x1811baa50 _dispatch_root_queue_drain + 540
24 libdispatch.dylib              0x1811ba7d0 _dispatch_worker_thread3 + 124
25 libsystem_pthread.dylib        0x1813b3100 _pthread_wqthread + 1096
26 libsystem_pthread.dylib        0x1813b2cac start_wqthread + 4

#16. co.kaishin.Gifu.preloadQueue
0  libsystem_pthread.dylib        0x1813b3e64 pthread_mutex_init + 638
1  ImageIO                        0x184075e44 initRecursivePthread_mutex + 68
2  ImageIO                        0x184075f38 CGImageMetadataCreateMutable + 192
3  ImageIO                        0x183fa10a0 IIOImagePlus::IIOImagePlus(CGImageReadSession*, void const*, __CFDictionary const*) + 476
4  ImageIO                        0x183fa0c80 CGImagePlusCreateWithSession + 164
5  ImageIO                        0x183f7c514 IIOImageSource::makeImagePlus(unsigned long, __CFDictionary const*) + 948
6  ImageIO                        0x183f7d514 IIOImageSource::getPropertiesAtIndexInternal(unsigned long, __CFDictionary const*) + 68
7  ImageIO                        0x183f7d494 IIOImageSource::copyPropertiesAtIndex(unsigned long, __CFDictionary const*) + 100
8  ImageIO                        0x183f800c4 CGImageSourceCopyPropertiesAtIndex + 188
9  Gifu                           0x101a1d1b0 _T0So13CGImageSourceC4GifuE10propertiess10DictionaryVySSSdGSgSi2at_tF + 52
10 Gifu                           0x101a1aed8 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_Tf4gn_n + 412
11 Gifu                           0x101a1ad28 _T04Gifu10FrameStoreC13prepareFramesyyycSgFyycfU_TA + 68
12 Gifu                           0x101a18c1c _T0Ix_IyB_TR + 36
13 libdispatch.dylib              0x1811aa9e0 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x1811aa9a0 _dispatch_client_callout + 16
15 libdispatch.dylib              0x1811b8ad4 _dispatch_queue_serial_drain + 928
16 libdispatch.dylib              0x1811ae2cc _dispatch_queue_invoke + 884
17 libdispatch.dylib              0x1811b8fa8 _dispatch_queue_override_invoke + 344
18 libdispatch.dylib              0x1811baa50 _dispatch_root_queue_drain + 540
19 libdispatch.dylib              0x1811ba7d0 _dispatch_worker_thread3 + 124
20 libsystem_pthread.dylib        0x1813b3100 _pthread_wqthread + 1096
21 libsystem_pthread.dylib        0x1813b2cac start_wqthread + 4

**Comment by nguyenquocdathcmus** [comment]
hi @mahmutsahinn  . I also have a this prolem . can you tell me how to fix it

**Comment by kaishin** [comment]
@mahmutsahinn @nguyenquocdathcmus Is any of you able to reproduce this locally? I can't make much from the crash report above and I am not familiar with it.
