### ISSUE TITLE
Demo crash

### ISSUE THREAD

**Issue by liwei5544** [kaishin/Gifu#120]
dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/weili/Library/Developer/Xcode/DerivedData/Gifu-ceouxxeuxkfitjfuqujdwowlaxzp/Build/Products/Debug-iphonesimulator/Gifu.framework/Gifu
  Reason: image not found

**Comment by kaishin** [comment]
Thanks for opening this issue. This was solved in 7d62700
