### ISSUE TITLE
How to share Gif?

### ISSUE THREAD

**Issue by ninjacn** [kaishin/Gifu#121]
```
let vc = UIActivityViewController(activityItems: [self.imageView.image ?? ""], applicationActivities: [])
vc.popoverPresentationController?.barButtonItem = sender as? UIBarButtonItem
present(vc, animated: true)
```
`self.imageView.image` is static.
`self.imageView.animationImages`  can't be shared

please help

**Comment by kaishin** [comment]
You should probably share its GIF `Data` object instead. You can also look into sharing it as a file with the .gif extension.

Either way, Gifu won't help you with sharing as its only supposed to animate GIFs. I can look into exposing a specific frame later on as a UIImage but not sure that will solve this problem.
