### ISSUE TITLE
animation wont start

### ISSUE THREAD

**Issue by yazankhayyat** [kaishin/Gifu#123]
Thank you for Gifu Im sure it works well and I might be missing something somewhere.
 
My GIF displays as the initial frame, but it never starts animating after calling the .startAnimatingGIF(). 

Below is my code:

class DiagnosisViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
    

    var diagnosisRowHeight = Height.diagnosisRow
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var accountPickerButton: UIButton!
    @IBOutlet weak var loadingView: UIView!
    @IBOutlet weak var calculatorGIF: GIFImageView!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.bringSubview(toFront: loadingView)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        calculatorGIF.startAnimatingGIF()
    }
    override func viewWillAppear(_ animated: Bool) {
        calculatorGIF.prepareForAnimation(withGIFNamed: "calculatorGIF.gif")
        getData()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        calculatorGIF.prepareForReuse()
    }

**Comment by GodriXx** [comment]
make sure your viewDidAppear and viewWillAppear works

`override func viewDidAppear(_ animated: Bool) {
super.viewDidAppear(animated)
    calculatorGIF.startAnimatingGIF()
}
override func viewWillAppear(_ animated: Bool) {
super.viewWillAppear(animated)
    calculatorGIF.prepareForAnimation(withGIFNamed: "calculatorGIF.gif")
    getData()
}
`

**Comment by kaishin** [comment]
As @GodriXx mentioned you should probably call super in your override. I will close this but please give an update if that didn't work for you.
