### ISSUE TITLE
UIKit on background thread

### ISSUE THREAD

**Issue by rob-nash** [kaishin/Gifu#128]
Hi Guys,

Just discovered this and it's awesome! Just stepping through the code and it's pretty nice. One issue though.

It looks like UIKit is being touched from a background thread here.

<img width="705" alt="screen shot 2018-05-26 at 14 34 08" src="https://user-images.githubusercontent.com/14126999/40576668-2c298ae2-60f2-11e8-9b75-ceb2001a12f8.png">

**Comment by kaishin** [comment]
Hi @rob-nash! Thank you for using Gifu 😉

`UIImage` is actually thread-safe.

> Because image objects are immutable, you cannot change their properties after creation. Most image properties are set automatically using metadata in the accompanying image file or image data. The immutable nature of image objects also means that they are safe to create and use from any thread.

[Source](https://developer.apple.com/documentation/uikit/uiimage)

**Comment by rob-nash** [comment]
I wouldn’t be so sure about that

https://twitter.com/steipete/status/748854187841220608?s=21

**Comment by kaishin** [comment]
If you are referencing to [this article](https://pspdfkit.com/blog/2016/investigating-thread-safety-of-uiimage/) then it's been fixed on iOS 10 according to the article itself. I will bump up the iOS requirement to 10.0 when iOS 12.0 is out of beta.
