### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by jklausa** [kaishin/Gifu#129]
Hey there! 

First release of Xcode 10 has come out yesterday, and unfortunately Gifu no longer builds under it. Thankfully, the one build error that there is has been already fixed in `master` by #125. It would be awesome if there was a new tagged release, so we didn't have to point to a `master` in our Podfile.

Thanks in advance!

**Comment by kaishin** [comment]
Done! https://github.com/kaishin/Gifu/releases/tag/v3.1.0
