### ISSUE TITLE
Xcode 10 Overlapping accesses to 'imageContainer', but modification requires exclusive access; consider copying to a local variable

### ISSUE THREAD

**Issue by helloniklas** [kaishin/Gifu#130]
Unable to compile in Xcode 10, Xcode 9 only throws a warning, but 10 won't compile.

```
imageContainer.image = activeFrame ?? imageContainer.image
```
Error: Overlapping accesses to 'imageContainer', but modification requires exclusive access; consider copying to a local variable

**Comment by azureric** [comment]
It is fixed in #125. As a workaround, you can manually point Gifu to `master` in your Podfile. 

I wish it can be tagged in a new release.

**Comment by kaishin** [comment]
The fix has been released as part of https://github.com/kaishin/Gifu/releases/tag/v3.1.0 🎊 Thanks to @maicki for the fix!
