### ISSUE TITLE
Xcode 10 common has been renamed error

### ISSUE THREAD

**Issue by tolgatanriverdi** [kaishin/Gifu#136]
Hi
Today I tried to build my project but gifu pod gave the below error. Do you know how to fix it?

common' has been renamed to 'runloopmode.commonmodes'

**Comment by kaishin** [comment]
Did you make sure to run the latest version?

**Comment by aznelite89** [comment]
I encountered the same issue on Xcode 10. 
Error : 'common' has been renamed to 'RunLoopMode.commonModes'

**Comment by aznelite89** [comment]
change swift version of the pod to swift 4.2 had fixed this issue.
