### ISSUE TITLE
Free YouTube Video Tutorial

### ISSUE THREAD

**Issue by rebeloper** [kaishin/Gifu#141]
Hi, I like Gifu so much that I have decided to create a video tutorial about it!
You can take a look at it here:

[https://youtu.be/I1HthQ2oxUI](https://youtu.be/I1HthQ2oxUI)

Let me know what you think. If you like it consider adding the link with this image to your README.

![Gif in UIImageView Swift 5 Thubmnail](https://user-images.githubusercontent.com/2488011/55828630-837da080-5b15-11e9-8ba8-609a8c04ee5f.png)

**Comment by kaishin** [comment]
Thanks @rebeloper. Sorry for the very late reply and thanks for your support!
