### ISSUE TITLE
building on iOS 8.3?

### ISSUE THREAD

**Issue by hijohnnylin** [kaishin/gifu#15]
The last release of GifU says “Make demo run on Xcode 6.3”, but I’m getting this error when doing carthage update:

$ sudo xcode-select -s /Applications/Xcode-Beta.app
$ carthage update
*** Fetching gifu
*** Fetching runes
*** Checking out gifu at “v0.8.2”
*** Downloading runes at “1.2.2: Extension compatibility”
*** xcodebuild output can be found in .../T/carthage-xcodebuild.Ey3mBh.log
*** Building scheme “Gifu” in Gifu.xcworkspace
2015-03-23 14:41:13.917 xcodebuild[69101:2742491] stream error: stream error at offset 29: created by an unsupported XCDependencyGraph build
** BUILD FAILED **

The following build commands failed:
 CompileSwift normal x86_64 .../Carthage/Checkouts/gifu/Source/Animator.swift
 CompileSwift normal x86_64.../Carthage/Checkouts/gifu/Source/ImageSourceHelpers.swift
 CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

How should I get carthage update to work for iOS 8.3?

**Comment by mbodge** [comment]
Having the same problem. Love this extension and hoping for a "swift" update.

**Comment by tiemevanveen** [comment]
I'm having the same problem, @hijohnnylin why did you close this issue? Did you find a solution?
