### ISSUE TITLE
CFBundleShortVersionString being set to last tag in parent repository while building with Carthage

### ISSUE THREAD

**Issue by lukkas** [kaishin/Gifu#157]
Currently, due to `Set Version Number` (I assume) build phase, problem may occur with Carthage builds. 

When Gifu is put to Carthage's Checkouts directory and then built, its Git repository is the one of project, that builds Gifu as its dependency. Therefore Gifu package ends up with CFBundleShortVersionString being set to last tag of containing project, rather than Gifu's actual version.

For me it went unnoticed for a long time, but recently, due to tag format that doesn't match AppStore requirements for bundle version, my built was rejected.

**Comment by kaishin** [comment]
I am very sorry to hear that. I will remove the `Set Version Number` in a future release.

**Comment by AvdLee** [comment]
I opened a PR fixing this!
