### ISSUE TITLE
iOS14 beta1 can't show gif

### ISSUE THREAD

**Issue by hootigger** [kaishin/Gifu#160]
iOS14 beta1,iPhone7 Plus
iOS14 beta1 can't show gif.

**Comment by jverdi** [comment]
Hey - I made a PR to try to deal with this:
https://github.com/kaishin/Gifu/pull/159

Do you want to give it a try and see if it solves the issue for you?

**Comment by hootigger** [comment]
@jverdi cool,the gif can be displayed normally.Thank you for solving my issue.
Device: iPhone8 iOS14 beta2.
