### ISSUE TITLE
Support iOS 14

### ISSUE THREAD

**Issue by yaakovgamliel** [kaishin/Gifu#162]
The library doesn't support iOS 14.
I did a couple of check and could not find the source of his issue, if someone can point me to the right class I can fix it and make a PR

**Comment by kaishin** [comment]
There is currently a PR for this: https://github.com/kaishin/Gifu/pull/159

**Comment by kaishin** [comment]
It's merged now. Try with the master branch.

**Comment by yaakovgamliel** [comment]
Thanks!

**Comment by yaakovgamliel** [comment]
Its working as expected, thank you for the quick response!
