### ISSUE TITLE
GIFs without Duration-Info play too fast

### ISSUE THREAD

**Issue by seemayr** [kaishin/Gifu#164]
For example, [this gif](https://file1.staging.mega.lol/pool/rdy/86078.gif) does not have the _duration_ field set in its Exif Informations (ExifTool does not print the Duration Field at all) - Compared to [this one for example](https://file1.staging.mega.lol/pool/rdy/85870.gif), which has a duration of 5.4 seconds. These GIFS are kind of rare, but they are definitely around.

Loading the data of the first gif into a GIFImageView and checking its gifLoopDuration in the completion handler, the gifLoopDuration holds a value of 0.1 - which would cause the GIF to play **super fast**. Seems like the default value for this field might be 0.1 and it won't be overwritten when the gif does not hold this information.
I think a higher default-value for _gifLoopDuration_ (or even better: a calculated value from the framecount and a specified default fallback framerate) would be a more versatile solution.

**Comment by kaishin** [comment]
I think this is a sensible suggestion. You are welcome to open a PR, otherwise I will try to take a look at it once other issues are tackled.

**Comment by seemayr** [comment]
I'll work on a PR, thanks.
