### ISSUE TITLE
iOS 14 GIFAnimatable UIKit extension doesn't play GIF

### ISSUE THREAD

**Issue by RemyLivewall** [kaishin/Gifu#167]
I have updated to the newest version of the library after noticing GIF's were no longer playing on iOS 14, but the issue persists with the implementation I use, which is basically the UIKit extension from: https://github.com/kaishin/Gifu#gifanimatable.

I have also replicated the fix that is implemented in the library itself in the extension, but to no avail.
```
    override open func display(_ layer: CALayer) {
        if UIImageView.instancesRespond(to: #selector(display(_:))) {
            super.display(layer)
        }
        updateImageIfNeeded()
    }
```

**Comment by ivoleko** [comment]
If you are using SPM, try to use master branch as source instead version. It seems that SPM still uses 3.2.2 as newest.

**Comment by RemyLivewall** [comment]
> If you are using SPM, try to use master branch as source instead major version. It seems that SPM still uses 3.2.2 as newest.

I am using CoocaPods and verified that I am using version 3.3, so unfortunately this doesn't solve the issue for me.

**Comment by SimeonRumy** [comment]
Currently, I am facing the same issue.

**Comment by RemyLivewall** [comment]
After looking into the issue a bit more it looks like the [CALayerDelegate](https://developer.apple.com/documentation/quartzcore/calayerdelegate) methods are called on iOS 13 and lower, but won't get called on iOS 14. They should be called after the animator receives a new frame:
```
extension GIFAnimatable {
  /// Calls setNeedsDisplay on the layer whenever the animator has a new frame. Should *not* be called directly.
  func animatorHasNewFrame() {
    layer.setNeedsDisplay()
  }
}
```

Adding the ```updateImageIfNeeded``` call results in animating GIF's. This proves the delegate methods don't get called, because they contain the ```updateImageIfNeeded``` call. I am not sure how to solve the problem properly, because the animatorHasNewFrame method is an internal extension in GIFAnimatable and is called internally from the Animator as well.

**Comment by kaishin** [comment]
Thanks for looking into this @RemyLivewall. I need to take a closer look at this. If you find anything please don't hesitate to update the issue.

**Comment by raffibedo** [comment]
I have the same problema, it doesn't play in iOS 14. In one case, it just show the first frame of the gif. Any idea?

**Comment by RemyLivewall** [comment]
I did some debugging with the iOS 13 and iOS 14 sims and the stack trace at the ```animatorHasNewFrame``` point is the same.
![GIFAnimatable-iOS13](https://user-images.githubusercontent.com/23557749/94776592-4c164a00-03c2-11eb-8f73-d8d1e4a0f3a6.png)
![GIFAnimatable-iOS14](https://user-images.githubusercontent.com/23557749/94776595-4caee080-03c2-11eb-9018-dd824161684a.png)

As mentioned before only iOS 13 proceeds to follow the expected path of calling the ```display(layer)``` method. I also changed my image views to GIFAnimatable views. As seen in this screenshot on iOS 13 it follows through to both the GIFImageView ```display(layer)``` and the UIImageView extension's ```display(layer)```.

![UIImageViewExtension-iOS13](https://user-images.githubusercontent.com/23557749/94776584-49b3f000-03c2-11eb-8218-4e3f36500379.png)

Unfortunately I don't have animated GIF's working on iOS 14 either which strikes me as odd. This unfortunately means I wasn't able to debug the process further. Even manually calling the ```display(layer)``` method for the ```animatorHasNewFrame``` method doesn't trigger it.

**Comment by baiRookie** [comment]
之前一直找不到图片加载不出来的原因，经过一番折腾，发现是UIimageView重写了display方法导致的，最后选择放弃使用此框架，因为UIimageView的继承使项目中其他的图片全部无法展示，最后使用SDWebImage加载，非常完美的解决了这个毛病，

**Comment by thebugcode** [comment]
As @baiRookie  says we Replaced Gifu with SDWebImage as we don't currently have the capacity to investigate all the ins and outs of gif loading. Might get involved in trying to solve the Gifu problem early next week but it's good to have a fallback

**Comment by CloseServer** [comment]
@kaishin 
How to solve the problem discussed above?

**Comment by Jinxiansen** [comment]
@kaishin 
How to solve the problem discussed above?

**Comment by kaishin** [comment]
I should have a fix by the end of the week. Thank you all for the help.

**Comment by Jinxiansen** [comment]
@kaishin 
Oh, great! 
Looking forward to your results! 
thank you very much!🍺🍺🍺

**Comment by RemyLivewall** [comment]
> I should have a fix by the end of the week. Thank you all for the help.

I found a fix for the problem. Changing the display layer method with the following fixes issues for displaying images and GIF's on my end:
```
override open func display(_ layer: CALayer) {
        guard let image = image else {
            return
        }
        layer.contentsScale = image.scale
        layer.contents = image.cgImage
        updateImageIfNeeded()
    }
```

I had issues with normal images no longer showing up either when building my app with Xcode 12. Which got me thinking and checking the original fix as implemented in other libraries. Because we are overriding the implementation of UIImageView in an extension some undefined behavior might be occurring and resulting in the strange behavior we are seeing since iOS 14 and/or Xcode 12.

Because we can't call super when overriding the base ```UIImageView``` class we have to implement both the original behavior and add our GIFAnimatable logic to the overriden method.

**Comment by KhoiNguyen1004** [comment]
> > I should have a fix by the end of the week. Thank you all for the help.
> 
> I found a fix for the problem. Changing the display layer method with the following fixes issues for displaying images and GIF's on my end:
> 
> ```
> override open func display(_ layer: CALayer) {
>         guard let image = image else {
>             return
>         }
>         layer.contentsScale = image.scale
>         layer.contents = image.cgImage
>         updateImageIfNeeded()
>     }
> ```
> 
> I had issues with normal images no longer showing up either when building my app with Xcode 12. Which got me thinking and checking the original fix as implemented in other libraries. Because we are overriding the implementation of UIImageView in an extension some undefined behavior might be occurring and resulting in the strange behavior we are seeing since iOS 14 and/or Xcode 12.
> 
> Because we can't call super when overriding the base `UIImageView` class we have to implement both the original behavior and add our GIFAnimatable logic to the overriden method.
> 
> EDIT: Do you want to send a pull request for the README.md with this change?

Hi I don't get what you mean, I am running to display a gift in a collectionViewCell, so I would use alamofire to download to data and use play gift with data with gifu, however you fixed way isn't for the collectionviewcell. Do you have any idea about it ?

**Comment by RemyLivewall** [comment]
@KhoiNguyen1004 The fix mentioned is only needed if you are using an extension (or category) on UIImageView. Because the original implementation seems to be lost on iOS 14. What kind of view are you using to show the GIC in you UICollectionViewCell?

**Comment by KhoiNguyen1004** [comment]
> @KhoiNguyen1004 The fix mentioned is only needed if you are using an extension (or category) on UIImageView. Because the original implementation seems to be lost on iOS 14. What kind of view are you using to show the GIF in your UICollectionViewCell?

I am using normal imageview, and make extension as example, I tried to implemented a custom class for gifu but it seems like doesn't work at all.

**Comment by alanpridestar** [comment]
Hi everyone, 

I don't think this issue should be closed. I attempted to follow the suggested solution, but similarly to Khoi, I am unable to play the gif in app. 

`class GifuImageView: UIImageView, GIFAnimatable {
	public lazy var animator: Animator? = {
	  return Animator(withDelegate: self)
	}()

	override open func display(_ layer: CALayer) {
		guard let image = image else {
			return
		}
		layer.contentsScale = image.scale
		layer.contents = image.cgImage
		updateImageIfNeeded()
	}
}`

Any suggestions would be greatly appreciated
Thanks

**Comment by RemyLivewall** [comment]
Are you using the GIFImageView, an extension on UIImage or a different method of trying to play the GIF files? Is it possible for you to share the code you were using before it worked?

**Comment by mikhailb1990** [comment]
I successfully got around this issue by updating the pod to version 3.3 and replacing animatedFrames with animationImages if that helps anyone.

**Comment by DamonHu** [comment]
As @RemyLivewall  said, the difference is that after I change the `image` to `activeFrame`, it works well. This is the code I modified

```
override public func display(_ layer: CALayer) {
        guard let image = self.activeFrame else {
            return
        }
        layer.contentsScale = image.scale
        layer.contents = image.cgImage
        updateImageIfNeeded()
 }
```

**Comment by viktorvrchlavsky** [comment]
@RemyLivewall @DamonHu Thank you guys for solving this 🙏

**Comment by dsrees** [comment]
FYI, updating Gifu to 3.3 resolved the issue for me.

**Comment by diegogarciar** [comment]
Hello, I'm still having this issue, I ran the example project and it works, but `UIImageViewExtension.swift` has no target, so just by setting a target to the file, the extension kicks in and the animation breaks

**Comment by monalisamarketing** [comment]
With 
```
override public func display(_ layer: CALayer) {
        guard let image = self.activeFrame else {
            return
        }
```
the gif works well but other images over the app are not displayed neither on testflight nor production
but with 
```
override public func display(_ layer: CALayer) {
        guard let image = image else {
            return
        }
``` the images are displayed but the gif is not displayed at all

**Comment by wjling** [comment]
Still have the problem that gif won't play. I test it on iOS 15

**Comment by sfandy126** [comment]
iOS 16.3 iOS 15.6 都无法正常播放gif，如何解决？

**Comment by sfandy126** [comment]
> 作为[@RemyLivewall](https://github.com/RemyLivewall)说，区别在于，在我将`image`更改为`activeFrame`后，它工作得很好。这是我修改的代码
> 
> ```
> override public func display(_ layer: CALayer) {
>         guard let image = self.activeFrame else {
>             return
>         }
>         layer.contentsScale = image.scale
>         layer.contents = image.cgImage
>         updateImageIfNeeded()
>  }
> ```

能解决iOS17以下GIF无法加载的问题！👍
