### ISSUE TITLE
SwiftPM Package Resolution Failed for v3.3

### ISSUE THREAD

**Issue by colemcampbell** [kaishin/Gifu#168]
Swift Package Manager doesn't seem to be picking up the newest version of Gifu, causing package resolution to fail if you try to update to v3.3.

`because no versions of Gifu match the requirement 3.3.0..<4.0.0 and root depends on Gifu 3.3.0..<4.0.0, version solving failed.`

**Comment by colemcampbell** [comment]
The reason seems to be that SwiftPM expects a three period separated integer for the version number like 3.3.0, but the version tag is 3.3.

```
Tag Your Latest Commit
It’s a best practice to create a version tag for a Swift package; however, there are other ways to add a package to a project, as described in Adding Package Dependencies to Your App. To create a version tag, tag the last commit with the package version. A package version is a three period-separated integer. An example is 1.0.0. The package version must conform to semantic versioning to ensure that your package behaves in a predictable manner when developers update their package dependency to a newer version.
```

**Comment by rval** [comment]
Running into the same thing. I was able to use SPM to install the `v3.3` branch, but it doesn't work with the tag.

**Comment by kaishin** [comment]
Fixed. Thanks @kean for the reminder!

**Comment by ManuEspeso** [comment]
@kaishin This changed breaks cocoapods installation, I've tried all possibilities (pod install, pod repo update, pod update ...) in a project with Gifu 3.3 and fails because cocoapods doesn't find any version with this tag

**Comment by kaishin** [comment]
I will push a fix momentarily.

**Comment by kaishin** [comment]
I restored the v3.3 tag for now. Sorry for the inconvenience.

**Comment by ManuEspeso** [comment]
Thanks for the quick response!
