### ISSUE TITLE
"image not found" error on startup

### ISSUE THREAD

**Issue by mbodge** [kaishin/Gifu#17]
Hey guys, first of all love the library. Was using and old version of it until Swift 1.2 came out and had to upgrade. Am using Carthage and the latest version (with the Int stuff fixed). I've simply added the Gifu and Runes frameworks to a blank project and added no code at all to the ViewController and I get this error when I start the app:

```
dyld: Library not loaded: @rpath/Gifu.framework/Gifu
  Referenced from: /Users/mike.bodge/Library/Developer/CoreSimulator/Devices/3C42811F-3BE4-41F9-BD11-EB414B5EF886/data/Containers/Bundle/Application/60858C28-E929-4DE0-AC45-8A3658FB7D26/TryGif.app/TryGif
  Reason: image not found
```

I haven't instantiated anything but it breaks right when the app loads. Any ideas?

**Comment by mbodge** [comment]
Ok I solved that by also adding the frameworks to the "embedded binaries" section of my app. Now i'm getting an error that "AnimatedImage" is an unresolved identifier. Any help would be super appreciated. Thanks again.

``` Swift
import UIKit
import Gifu

class ViewController: UIViewController {

    @IBOutlet weak var imgStatic: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        if let image = AnimatedImage.animatedImageWithName("static.gif") {
            imgStatic.setAnimatedImage(image)
            imgStatic.startAnimatingGIF()
        }
        
        
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}
```

**Comment by SamBuydens** [comment]
I had the same issue, here is what I did to initialize a gif.

```swift
        var bus = AnimatableImageView()
        bus.frame = CGRectMake(0, 0, 320, 200)
        bus.animateWithImage(named:"bus.gif")
        bus.startAnimatingGIF()
        self.addSubview(bus)

```

**Comment by muhasturk** [comment]
You need to fix your code

```swift
self.view.addSubview(bus)
```

**Comment by kaishin** [comment]
Please use `1.2.1` and `AnimatableImageView` going forward. Older versions of Swift are no longer be supported .
