### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by Danie1s** [kaishin/Gifu#173]
![QQ20210319-130649](https://user-images.githubusercontent.com/19432029/111738676-b8c3c900-88bc-11eb-9856-4dc44266187c.png)
![QQ20210319-130716](https://user-images.githubusercontent.com/19432029/111738681-bb262300-88bc-11eb-883a-1bab291428eb.png)

**Comment by kean** [comment]
I sometimes get this crash as well, will update the comment if I figure out the reason.
