### ISSUE TITLE
Support other image formats

### ISSUE THREAD

**Issue by kean** [kaishin/Gifu#177]
I suggest adding an option to extend the framework to add other image decoders, e.g. WebP, APNG. Most of the display logic can be presumably reused across the formats.

There [were](https://github.com/Flipboard/FLAnimatedImage/pull/86) [attempts](https://github.com/Flipboard/FLAnimatedImage/pull/143/files) to extend FLAnimatedImage to support additional formats, but none of them got merged. I don't know if there exists a framework that does these things without also bundling a massive image loading and caching library with it.

**Comment by eliburke** [comment]
Core Image supports GIF natively. That's the display logic. Gifu just makes it play nice with Swift.
