### ISSUE TITLE
Version number is wrong in ppdspec file for 3.4 release

### ISSUE THREAD

**Issue by praveenkumarsomu** [kaishin/Gifu#187]
I'm not able to upgrade to 3.4 this may be because In your latest release 3.4 podspec file version number is 3.3.1. 

[!] CocoaPods could not find compatible versions for pod "Gifu":
  In Podfile:
    Gifu (= 3.4)

None of your spec sources contain a spec satisfying the dependency: `Gifu (= 3.4)`.

**Comment by kaishin** [comment]
Good catch. Fixing.

**Comment by kaishin** [comment]
Fixed in 82da0086dea14ca9afc9801234ad8dc4cd9e2738.

**Comment by bhadreshtechinnate** [comment]
I am not able to update to latest version 3.4.

**Comment by kaishin** [comment]
For those still encountering this issue please use a more recent version.
