### ISSUE TITLE
Build failes due to Swift Compiler Error

### ISSUE THREAD

**Issue by izkrivera** [kaishin/Gifu#19]
/gifu/Animator.swift:3:8: No such module 'Runes'

Xcode 6.3.1
target iOS 8.3

**Comment by TarangKhanna** [comment]
Download the framework Runes, you can do so by installing carthage and running 'carthage update'. Make sure your cartfile has - github "thoughtbot/runes"
and if u want gifu also include - github "kaishin/gifu"
Hope that helps.

**Comment by izkrivera** [comment]
Thanks, instead I installed Carthage and used it to build Gifu, I get no compiler errors on the Xcode editor but on build I get "Unknown class AnimatableImageView in Interface Builder file." for the following code:

@IBOutlet weak var preloaderView: AnimatableImageView! {
	didSet {
		preloaderView.animateWithImage(named: "gt_logo_314.gif")		
	}
}

**Comment by izkrivera** [comment]
Never mind it was a Carthage issue.

**Comment by izkrivera** [comment]
Resolved. It was a Carthage issue.

**Comment by lmacfadyen** [comment]
izkrivera, can you elaborate on what the issue was with Carthage?  I have the same issue and haven't found the cause yet.  Was wondering if you stopped using Carthage or was it a configuration issue with it?  Thanks!

**Comment by izkrivera** [comment]
I updated Carthage to the latest build and deleted all Cartage project files and started all over. I also had to be careful about specifying the file locations for compilation. It works now. Does this help? Otherwise I can open up the project a bit later and check the exact pathing information.

**Comment by lmacfadyen** [comment]
Thanks for blazingly fast response on a weekend! I had used latest Carthage, and this ended up being a user error on my part...hadn't added the Gifu module in Interface Builder where I have my AnimatableImageView subclass of UIImageView. AnimatableImageView doesn't show up in classes but I specify it anyway and it works. Thanks very much.
