### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by itsdan** [kaishin/gifu#20]

**Comment by samuelbeek** [comment]
+1

**Comment by lizhijun** [comment]
+1

**Comment by Lxrd-AJ** [comment]
+1

**Comment by callmewhy** [comment]
+1...

**Comment by rhenz** [comment]
+1

**Comment by dongkaipo** [comment]
+1

**Comment by xing-ou** [comment]
+1

**Comment by yurijmi** [comment]
+1

**Comment by OlafAndreas** [comment]
+1

**Comment by jungtong** [comment]
+1

**Comment by thunderousNinja** [comment]
:+1:

**Comment by tonyd256** [comment]
Hey all, would anyone want to PR a podspec for this? We can eventually get to it but we could get it sooner if anyone has some spare cycles to help out. Thanks in advance!

**Comment by thunderousNinja** [comment]
I'll have some spare time to do it this weekend if no one else does it by then.

**Comment by kaishin** [comment]
Added the podspec but I am having issues with validating it due to the Runes submodule dependency.

**Comment by kaishin** [comment]
Done and done.

**Comment by thunderousNinja** [comment]
nice!
