### ISSUE TITLE
Huge memory usage

### ISSUE THREAD

**Issue by SamBuydens** [kaishin/Gifu#22]
This frameworks usages enormous amounts of memory, running the app in instruments even goes up to 335mb...

**Comment by mrigdon** [comment]
Is there a reason for this closure? I've found this memory issue too and it's a gaping hole. For some reason gifs are NOT being deallocated after they're done. How is this not being addressed?

**Comment by kaishin** [comment]
@mrigdon This should be fixed in 2.0.

**Comment by kaishin** [comment]
I will close once the official release is live.
