### ISSUE TITLE
Gifu For Swift 2

### ISSUE THREAD

**Issue by lmacfadyen** [kaishin/gifu#26]
For me Gifu isn't working under Swift 2. I assume it isn't updated yet but can anyone else confirm that this is currently expected?

Thanks!

**Comment by kaishin** [comment]
Updated now in master.

**Comment by lmacfadyen** [comment]
Thanks for the updates. I use Carthage to build, and it updates Runes, but I can't seem to get it to update Gifu. Still seems to be Swift 1.2. In Headers directory, Gifu-Swift.h it has Swift 1.2. Using Sources there are operator compile errors. Should carthage update be resulting in Swift 2.0?

**Comment by kaishin** [comment]
@lmacfadyen I haven't released 1.0.0 yet (still working on docs). Use `"kaishin/gifu" "master"` in your Cartfile for now. Runes is no longer a dependency so you can remove it from your project if you are not using it in your own code.

**Comment by lmacfadyen** [comment]
Thank you for a fast response! Really appreciate it and will update to master that way. Cheers!
