### ISSUE TITLE
error ：dyld: Library not loaded: @rpath/libswiftSecurity.dylib

### ISSUE THREAD

**Issue by zyg-github** [kaishin/Gifu#27]
error ：dyld: Library not loaded: @rpath/libswiftSecurity.dylib

libswiftSecurity.dylib ？？

**Comment by jackywang135** [comment]
There is an "Embedded Content Contains Swift Code" flag in the Build Settings that needs to be set to YES. It was NO by default.

**Comment by bpillon** [comment]
My "Embedded content contains swift code" is set to YES but I have the same problem.

**Comment by kaishin** [comment]
Closing this for now. Please use the latest version and reopen if this persists.
