### ISSUE TITLE
Any support to get duration of gif file

### ISSUE THREAD

**Issue by fouadkada** [kaishin/Gifu#30]
is it currently possible to get the duration of the animation in the gif file?

**Comment by kaishin** [comment]
No it is not. It could be something that the API exposes though. What you need that info for?

**Comment by fouadkada** [comment]
i am trying to use the project to display a gif as a splash screen, it would be nice to get the duration of the animation to start a new viewcontroller after a specific duration

**Comment by kaishin** [comment]
Yes, that is not unreasonable.

**Comment by fouadkada** [comment]
i am following the same approach on the android version of my project and for that i am using this project
and that project exposes this set of APIs
```
stop() - stops the animation, can be called from any thread
start() - starts the animation, can be called from any thread
isRunning() - returns whether animation is currently running or not
reset() - rewinds the animation, does not restart stopped one
setSpeed(float factor) - sets new animation speed factor, eg. passing 2.0f will double the animation speed
seekTo(int position) - seeks animation (within current loop) to given position (in milliseconds)
getDuration() - returns duration of one loop of the animation
getCurrentPosition()
```

they also expose an event listener that is triggered on animation completion which can be used to start a new controller
this is the equivalent in android
````
gifDrawable.addAnimationListener(new AnimationListener() {
                @Override
                public void onAnimationCompleted() {
                    Log.d(TAG, "splash screen animation complete...starting activity");
                    if (gifDrawable.canPause()) {
                        gifDrawable.pause();
                    }
                    Intent i = new Intent(SplashScreen.this, MainActivity.class);
                    startActivity(i);
                }
            });
```

it would be nice to have something similar

**Comment by kaishin** [comment]
Thanks for sharing this @fouadkada. I had thought about adding some of these and this is a good reference. I'd happily welcome PRs as well.

**Comment by cprovatas** [comment]
+1 on this as well.  I'm working in a project that is dependent on showing a new view controller when the gif image has finished.  It would be great for this to be dynamic instead having to manually find out the duration of the gif file.

**Comment by kaishin** [comment]
This can be done using `GIFAnimatable.gifLoopDuration` starting https://github.com/kaishin/Gifu/releases/tag/v3.0.0 😉 It used to be there before but didn't work properly if called immediately after calling any of the `animate()` functions.
