### ISSUE TITLE
Bad scrolling performance 

### ISSUE THREAD

**Issue by mitchellporter** [kaishin/Gifu#34]
I installed this late last night and wanted to see how it matched up against FLAnimatedImage. Not sure if this has anything to do with my particular setup but the scrolling performance was very "jittery". Sometimes it was smooth, other times the scroll motion would get stuck for a second and then become unstuck.

For my setup I had a collection view with a with a Gifu image view in each cell. When not scrolling, I was very impressed with the low CPU and memory usage so congrats on that, but it seems like special adjustments need to be made to accommodate scrolling.

**Comment by kaishin** [comment]
Hi @mitchellporter. I think some of it has to do with the lack of a proper way to prepare the images for reuse. This should solve the issue (hopefully) once merged https://github.com/kaishin/Gifu/pull/33

**Comment by mitchellporter** [comment]
@kaishin Sounds great!

**Comment by Monte9** [comment]
@kaishin Can you please merge #33? I am having the same problem with scrolling and its not fun to use.

**Comment by kaishin** [comment]
Done.

**Comment by kaishin** [comment]
@Monte9 @mitchellporter Try again with `v1.1.0`. If the problem persist, your code needs to be optimized (when you get the image data, on which thread, do you cache the data, etc). I'm afraid that is not something that Gifu can do for you.

**Comment by Monte9** [comment]
Ok got it. Thanks.

**Comment by kaishin** [comment]
Closing this for now. If anyone has more concrete data using `1.2.1` please reopen.
