### ISSUE TITLE
resizing results in bad compression

### ISSUE THREAD

**Issue by Richard-Barbat** [kaishin/Gifu#36]
I have created an UIImageView with autolayout-constraints in storyboard and set the class to AnimatableImageView. Everything works fine, the gif is animating well. The viewmode is set to"Aspect Fit" because the original gif is actually bigger than the screen but after resizing the quality of the image has suffered. Is there a way to keep the quality of the gif as good as possible?

**Comment by kaishin** [comment]
Fixed in #40.
