### ISSUE TITLE
No error, but no image displays

### ISSUE THREAD

**Issue by AarioAi** [kaishin/Gifu#44]
`
let savingLoading = AnimatableImageView(frame: CGRect(x: UIScreen.mainScreen().bounds.width - 60, y: UIApplication.sharedApplication().statusBarFrame.height, width:300, height:30))
        savingLoading.animateWithImage(named: "loading1.gif")
        savingLoading.startAnimatingGIF()
        self.view.addSubview(savingLoading)
`
Why no image displays?

**Comment by orangenpresse** [comment]
I found out that you get no error if your image is not found.
First I had my image added to my assets. Then no error and no image appeard.

After added the gif to the project itself, everything worked.
Hope this helps.

**Comment by lumo2707** [comment]
I had the same issue. If I create an object of AnimatableImageView and add add the reference to the gif nothing happens.

`            let imageView = AnimatableImageView(frame: CGRectMake(0,0,150,150))
            self.view.addSubview(imageView)
            imageView.animateWithImage(named: "mugen")
            imageView.snp_makeConstraints(closure: { (make) -> Void in
                make.center.equalTo(self.view)
            })`

I have tested it with the mugen.gif ;) Before i added it to the assets. @orangenpresse  where do you put the gif into the project?

**Comment by orangenpresse** [comment]
@lumo2707  With File -> Add Files to "Your Projectname"

**Comment by SimenZhor** [comment]
Thanks @orangenpresse, this solved my issues
