### ISSUE TITLE
Doesn't compile on newest Swift version

### ISSUE THREAD

**Issue by hevselavierlines** [kaishin/Gifu#45]
Hello, I was trying your project in the newest Xcode version, however, the project didn't compile due to some changes.
* New operators need to be declared with infix operator >>- {associativeity left precedence 160)
* The Interface builder needs to create a new UIView for the AnimatedImageView otherwise the app crashed
* Import UIKit almost everywhere.
With these improvements everything worked fine in the end.

**Comment by storix** [comment]
What Xcode version exactly do you have? My version is 7.2.1 and it compiles just fine.

**Comment by startupthekid** [comment]
I have 7.2.1 as well and it doesn't compile. If I import Gifu, Xcode says `Cannot load underlying module for Gifu`.

@hevselavierlines then I cleaned Xcode and everything built/worked just fine. Try doing a clean and then re-building your entire project.

**Comment by kaishin** [comment]
Bothe the framework and the demo are running fine on Xcode 7.3 and Swift 2.2. @hevselavierlines Please provide more info or close the issue if you are able to run it now.

**Comment by rayfix** [comment]
@kaishin Great project!  My 2 cents.  So when I download the tar ball and open the workspace it looks like it depends on the Runes project.  (There is a missing source file Runes.swift)  Runes.swift appears to provide the infix and precedence of the functional operators <^> <*> >>-.  I am guessing @hevselavierlines did not use Carthage or Cocoapod which resulted in errors.  You are so close to breaking off the Runes dependency, seems like it would be win to do so.

**Comment by kaishin** [comment]
@rayfix Yes, dropping the Runes dependency is the plan. Thanks!
