### ISSUE TITLE
Animation is playing after calling prepareForAnimation

### ISSUE THREAD

**Issue by storix** [kaishin/Gifu#48]
Hi, guys. I've just encountered an issue with the prepareForAnimation method:  documentation states that it prepares the frames **without** starting the animation. But in my app it starts playing anyway. Do you have this behaviour too?

**Comment by kaishin** [comment]
That doesn't sound right. All it does is attach the display link, without **unpausing** it. Are you sure you can isolate this?

**Comment by storix** [comment]
Ok, i tried to change [this line](https://github.com/kaishin/Gifu/blob/ad67756cefd7fde1727e3d1ad00459c29e4f9f06/Demo/demo/classes/ViewController.swift#L10) in the Demo project to this:
`    imageView.prepareForAnimation(imageNamed: "mugen.gif")
`
and it starts playing...Is this intended behavior?

**Comment by kaishin** [comment]
@storix No it isn't. I'll take a look at this.

**Comment by storix** [comment]
You know, I resolved the issue. According to the [Apple's docs](https://developer.apple.com/library/ios/documentation/QuartzCore/Reference/CADisplayLink_ClassRef/#//apple_ref/occ/instp/CADisplayLink/paused) the default value of the `pause` property is false. So, i just added this line 
`displayLink.paused = true`
before [this](https://github.com/kaishin/Gifu/blob/master/Source/AnimatableImageView.swift#L43) and it works fine ^_^

This is just one-line change, should I submit PR or you will handle it yourself?

**Comment by kaishin** [comment]
@storix I have a PR ready! Feel free to review it and I'll merge it.
