### ISSUE TITLE
pod cannot update to v1.1.0

### ISSUE THREAD

**Issue by MingLoan** [kaishin/Gifu#60]
In my Podfile, I added pod 'Gifu', but it always get v1.0.1 instead of the new one.

**Comment by MingLoan** [comment]
Quick fix:
pod 'Gifu', :git => 'https://github.com/kaishin/Gifu.git', :commit => '310377c'

**Comment by kaishin** [comment]
The podfile is a bit out -of-date. I will fix that once #59 is merged.

**Comment by MingLoan** [comment]
pod 'Gifu' still install v1.0.1

**Comment by MingLoan** [comment]
your pod spec still pointing to 1.0.1 ...
