### ISSUE TITLE
Somehow Gifu memory address not being deallocated

### ISSUE THREAD

**Issue by zheref** [kaishin/Gifu#69]
I'm profiling an application, and found out several Gifu memory addresses that are still allocated even when I already stopped the animation and made the AnimatableImageView instance nil.

<img width="424" alt="screen shot 2016-06-02 at 7 38 36 pm" src="https://cloud.githubusercontent.com/assets/1177000/15765365/aa0dcf8c-28f9-11e6-94f3-ec0d811da575.png">

It has become a bigger memory leak in my application since it's wasting almost half of what my app is actually using for its purposes.

Any further information I can provide, I will be aware.

Thanks in advance.

**Comment by mrigdon** [comment]
Having this issue too. This is huge and really bad

**Comment by mrigdon** [comment]
@zheref Did you find a fix for this? It's causing my app to crash.

**Comment by zheref** [comment]
Me too. We had to change to another library :(

**Comment by joelrfcosta** [comment]
Same here :(

**Comment by DavidLari** [comment]
@zheref What library did you switch to?

**Comment by zheref** [comment]
I switched to:
FLAnimatedImage (https://github.com/Flipboard/FLAnimatedImage)

**Comment by kaishin** [comment]
@zheref @mrigdon Thank you for opening an issue. I will investigate but would appreciate it if people helped debug this.

**Comment by kaishin** [comment]
This has been fixed in the Swift 3 branch https://github.com/kaishin/Gifu/tree/swift3
