### ISSUE TITLE
Swift 2.3 compatibility required

### ISSUE THREAD

**Issue by evgeniyd** [kaishin/Gifu#72]
While we are all enabled to use Xcode 8 with Swift 2.3 toolchain, the project has to be refactored in order to support this.

So far, the workaround to actually build the library with Carthage and Xcode 8 is:

1. Fix the project to build with Swift 2.3
2. Run the following commands:
    
    `$carthage update --use-submodules --no-build`
     `$TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage build`

**Comment by evgeniyd** [comment]
This is a pull request with the changes #73

**Comment by kaishin** [comment]
@evgeniyd Thank you for opening the PR. I am currently focusing on Swift 3 support and will probably won't have time to back port. If you want to tackle this please wait until the final 2.0 release to minimize the amount of work you will have to do.

**Comment by kaishin** [comment]
@evgeniyd I pushed support for 2.3 in the [swift2.3](https://github.com/kaishin/Gifu/tree/swift2.3) branch. That branch will not be merged with master and should only be used in case upgrading to Swift 3 is not an option. Closing this for now.
