### ISSUE TITLE
Not compatible with deployment target iOS 9

### ISSUE THREAD

**Issue by chickdan** [kaishin/Gifu#75]
I've been working on an app with a deployment target of iOS 9. Unable to get gifs to load (they wouldn't display at all) I took a look at the demo and saw the deployment target was iOS 8. I switched and it works. Not a huge issue, but an issue none-the-less.

**Comment by buiminhhuy** [comment]
Me too

**Comment by morganzysman** [comment]
same here

**Comment by aaronpearce** [comment]
Just noticed this myself. Strange issue.

**Comment by aaronpearce** [comment]
iOS9 organizes its `.xcassets` as a compressed file `Assets.car` wheres iOS8 just puts the assets from the `.xcassets` directly in the main bundle.

This causes the below method to fail as there is no file at the `imagePath` generated as on iOS9 it is in the `Assets.car` file.

```public func prepareForAnimation(imageNamed imageName: String) {
    let imagePath = NSBundle.mainBundle().bundleURL.URLByAppendingPathComponent(imageName)
    guard let data = NSData(contentsOfURL: imagePath) else { return }
    prepareForAnimation(imageData: data)
  }```

As a workaround to this when building as iOS9 as the deployment target, GIFs need to be put directly into the project not into the .xcassets.

**Comment by kaishin** [comment]
I will look into this before finalizing the 2.0 release.
