### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by odedharth** [kaishin/Gifu#78]
not compatible with Swift 3 😕

**Comment by kaishin** [comment]
I started working on compatibility here but it's still not updated to the final release yet: https://github.com/kaishin/Gifu/tree/swift3 I will try to tackle this this week and finalize the release.

**Comment by Mosaics** [comment]
What time support wsift3?

**Comment by run4jit** [comment]
any update when we can get update for swift 3.0

**Comment by kaishin** [comment]
@run4jit [The swift3 branch](https://github.com/kaishin/Gifu/tree/swift3) now works with release Swift 3 so feel free to use it for now until the API is finalised. Currently testing performance and memory leaks + backward compatibility.

**Comment by kaishin** [comment]
Everything seems to be working fine so far on device. Simulator throws some warnings and has some frame issues but I am not worried about that. Tested on a 2013 iPod touch and worked like a charm.
Next is going to be several API changes to make using the library easier and more flexible.

**Comment by xkenpachi** [comment]
There is still warnings and errors on my project. For example Animator.swift has error on 42. line

**Comment by xkenpachi** [comment]
Actually i passed that errors but gifs are very speedy, how can i slow them? I have 2 frame gifs

**Comment by kaishin** [comment]
@xkenpachi If you are still getting errors under 3.0 please let me know. I have fixed all of them as far as I am concerned.

Slowing GIFs is not supported and will not be in the forseeable future. If you have control over the GIF, do that when you export it.

**Comment by xkenpachi** [comment]
@kaishin errors solved, thanks. In swift 2.2 gifs are worked perfectly, i don't think its about gifs because they working normal any html explorer or in finder preview or in xcode preview.

**Comment by matrosovDev** [comment]
I am not sure if I did all rights. But it trows an error and says that method does not override anything 

/// Updates the `image` property of the image view if necessary. This method should not be called manually.
  override open func displayLayer(_ layer: CALayer) {
    image = animator?.currentFrameImage ?? image
  }

**Comment by xkenpachi** [comment]
@matrosovDev you just need the to do like this:

override open func display(_ layer: CALayer) {
    image = animator?.currentFrameImage ?? image
  }

**Comment by kaishin** [comment]
Swift 3 support is now merged into `master`.
