### ISSUE TITLE
AnimatableImageView

### ISSUE THREAD

**Issue by odedharth** [kaishin/Gifu#81]
seems that AnimatableImageView has been replaced in the Swift 3 branch.

`let imageView = AnimatableImageView(frame: CGRect(...))`

How should it be replaced?

**Comment by kaishin** [comment]
@odedharth You can use `GIFImageView` instead. The documentation will updated and will include a migration guide as well.

**Comment by odedharth** [comment]
@kaishin How do you initialize it programmatically?

**Comment by kaishin** [comment]
@odedharth Just like any `UIImageView`: using `frame` or `image`.

**Comment by kaishin** [comment]
@odedharth Example here: https://github.com/kaishin/Gifu/tree/swift3#examples
