### ISSUE TITLE
source files loaded with Cocoa pod bring a lot of Swift3 error messages

### ISSUE THREAD

**Issue by ujikol** [kaishin/Gifu#83]

**Comment by kaishin** [comment]
Are you pulling from master?

**Comment by ujikol** [comment]
Obviously not. I just included: `pod 'Gifu'`
If I interpret the readme correctly then should do the trick.

**Comment by kaishin** [comment]
@ujikol Sorry for the misunderstanding. You are using an older version of the library which doesn't support Swift 3. In order to fix that, you can use an unreleased version by doing this instead:

```
pod 'Gifu', :git => 'https://github.com/kaishin/Gifu.git'
```

**Comment by ujikol** [comment]
That works. thx
