### ISSUE TITLE
Swift3 animate(withGIFData:) crash

### ISSUE THREAD

**Issue by iantheparker** [kaishin/Gifu#85]
Here's my call

```
if let data = NSData(contentsOf: file.url.path) as? Data, file.url.lastPathComponent.contains(".gif"){
             >>>>> iv.animate(withGIFData: data)
}
```
And this is where the crash is pointing to 

<img width="728" alt="screen shot 2016-10-10 at 7 06 10 pm" src="https://cloud.githubusercontent.com/assets/1368966/19253925/a8521886-8f1c-11e6-904d-098ec733634d.png">

**Comment by kaishin** [comment]
@iantheparker That is unfortunately not enough to pinpoint the cause. Do you see anything in the console? Which thread is this running on? How are you importing Gifu in your project?

**Comment by iantheparker** [comment]
Sorry about that. I've been catching a lot of bugs in swift3 branches lately and I was a bit too hasty here. The console was just giving me completely generic crash info. I'm using this in iOS 10's notification content extension and initializing the GIFImageView in a storyboard. I'm able to load a gif by name, and I'm able to display a static image via data/file, but whenever I try and load the same data through withGIFData I get that generic crash and message. SwiftyGif gave me problems because it needed to access the shared UIApplication's keyWindow, which a content extension can't access, so I wasn't sure if there's something similar to that happening here.

**Comment by kaishin** [comment]
@iantheparker Thanks for the info. I would love to take a look but I need to reproduce this. I remember that depending on how the file is included in the project it might not work. 

If you can share a minimal reproduction case that would be awesome, otherwise I'll try to reproduce this on my won.

**Comment by Drenadan** [comment]
@kaishin i have the same issue like @iantheparker when I use UITableView and my GIFImageView connected like CustomTableViewCell, so if I try to animate for example  cell.contentImage.animate(withGIFData: data1 as Data) I will have the same error like in first massage

**Comment by Drenadan** [comment]
@kaishin newer mind, I found the problem in my case.

It's related to custom class, in storyboard need to choose GIFImageView and module Gufu instead of UIImageView, and after that gufu will work.

![screen shot 2016-10-24 at 12 45 52 am](https://cloud.githubusercontent.com/assets/13716043/19629730/a214eac2-9983-11e6-9b88-72019ef42e2a.png)

**Comment by Drusy** [comment]
I confirm, this crash happen when you are using storyboard / xib to instanciate a `GIFImageView`. Xcode is not choosing any module (or even proposing or warning anything). So forcing the module to `Gifu` fix this.
