### ISSUE TITLE
animation does not run if GIFImageView is in a loaded xib file

### ISSUE THREAD

**Issue by gvlachos** [kaishin/Gifu#96]
I am using xcode 8.2.1 and swift 3

in my view controller in viewDidLayoutSubviews if I initialise a GIFImageView as follows

```
        self.image = GIFImageView()

        self.image.contentMode = .center

        self.image.isHidden = false

        self.image.prepareForAnimation(withGIFNamed: "image_name_a")

        self.image.startAnimatingGIF()

        self.image.frame = CGRect(
            x: 0, y: 0,
            width: view.bounds.width, height: view.bounds.height)

        self.view.addSubview(self.image)
```

then the gif is displayed and animation runs successfully, however

if instead, in the same place (viewDidLayoutSubviews), I load the GIFImageView from a xib file and do the following

```
       let bundle = Bundle(for: type(of: self))

        self.image = {
            let nib = UINib(nibName: "image", bundle: bundle)
            let view = nib.instantiate(withOwner: self, options: nil).first as! GIFImageView
            return view
        }()

        self.image.isHidden = false

        self.image.startAnimatingGIF()

        self.image.frame = CGRect(
            x: 0, y: 0,
            width: view.bounds.width, height: view.bounds.height)

        self.view.addSubview(self.image)
```

then the gif is displayed but the animation is not running.

I have attached the xib file (GIFImageView.txt).

Am I missing some initialisation for the xib file ?

[GIFImageView.txt](https://github.com/kaishin/Gifu/files/687613/GIFImageView.txt)

**Comment by kaishin** [comment]
@gvlachos In the second code snippet, I do not see `self.image.prepareForAnimation(withGIFNamed: "image_name_a")`, are you doing it elsewhere?

**Comment by gvlachos** [comment]
@kaishin ah yes, you are right, I missed this. In the xib file, I am using a variation so that a different image is displayed for a compact width than a regular width. So I need to find the image image currently displayed and call prepareForAnimation on it.
