### ISSUE TITLE
Having an issue switching from normal image to Gif

### ISSUE THREAD

**Issue by chickdan** [kaishin/Gifu#97]
Until the release of Gifu 2.0 I had been using the old Swift 2.3 branch and it's worked for my needs. However, I just converted my codebase to Swift 3 and have been having issues. I am trying to switch an image in a GIFImageView from a .png to a .gif, it worked fine before but now it is not and I haven't been able to figure out why. 

prepareForReuse() was crashing the app. I tried two different things that stopped the crash but still wouldn't change the image. The first thing I tried was going to the stopAnimation() function and putting an animatable check similar to startAnimation(), this stopped the crashing but wouldn't update the image. Second I went to the GIFAnimatable class and put animator = nil in the prepareForReuse() function (mimicking the old codebase). This produced the same results as the first attempt.

My code is as follows:

    mainImage: UIImage! 
   
    func changeImage(_ sender: UISegmentedControl) {
        switch sender.selectedSegmentIndex {
        case 1:
            imageView.prepareForReuse()
            imageView.animate(withGIFNamed: "\(name).gif")
        case 0:
            imageView.prepareForReuse()
            imageView.image = mainImage
        default:
            imageView.prepareForReuse()
            imageView.image = mainImage
        }
    }

I'm not sure if there is a bug, missing functionality, or I am doing something wrong but as I said this works with the Swift 2.3 branch. Any help is appreciated, thank you.

**Comment by kaishin** [comment]
Thanks for opening the issue @chickdan. I will try to reproduce this and report back.

**Comment by kaishin** [comment]
@chickdan I am unable to reproduce the issue. Here is a screen recording of a quick demo I built to test this:

![toggle](https://cloud.githubusercontent.com/assets/519433/21870958/76b10a94-d85f-11e6-850a-ef818f9da34a.gif)

Could you provide some more info like console output?

**Comment by chickdan** [comment]
Unfortunately there is no console output. If I use prepareForReuse() it crashes either at line 90 in GIFAnimatable.swift or the line in which I call the function in my code. If I do not use it then it crashes at line 57 of GIFAnimatable.swift.

Both crashes only give EXC_BAD_ACCESS errors.

**Comment by chickdan** [comment]
@kaishin I have tried creating a new app as you did and I'm still having issues. Sometimes it does not crash but does not update the image view either, other times it crashes on prepareForReuse().

**Comment by kaishin** [comment]
@chickdan Can you please share the app or code?

**Comment by chickdan** [comment]
@kaishin here you go: 

https://drive.google.com/open?id=0B2KgY_2tIcgPdHRqUExhbE1lZmM

**Comment by kaishin** [comment]
@chickdan The issue here is due to not setting `GIFImageView` as the custom class of the image view in Interface Builder. The second issue is that loading GIFs from the Assets is unsupported/untested.

**Comment by chickdan** [comment]
@kaishin Oops, forgot to set it in the test app but it was already set in the actual application I'm working on. I moved the two images to the project outside of Assets, still crashing. Then added them to "Copy Bundle Resources" under Build Phases, still crashing. How do I add them to the main bundle? I'm still quite new to iOS and this really doesn't make any sense considering the Assets folder has been (according to everything I've read) the standard way to store images since iOS 7.

**Comment by kaishin** [comment]
@chickdan Sorry for the late response. After some investigation, it appears like Assets does not have proper support for GIF and you need to manually change the JSON file to add a GIF image. Even with that however, I was unable to make this work successfully.

Can you please upload the updated version of the test app with the changes you've made? It worked for me when I did the 2 changes I outlined above.

**Comment by chickdan** [comment]
@kaishin Here is the download link: https://drive.google.com/open?id=0B2KgY_2tIcgPNFRNb1R4U0Frclk

It's a hit and a miss whether or not the app crashes or the image doesn't update.
